#!/usr/bin/env python3
"""Generate the GBA IDE runtime's built-in 8x8 text font as 4bpp GBA tile data.

Rasterises ASCII 32..126 from DejaVu Sans Mono into 8x8 1-bit cells, packs each
as a 4bpp GBA tile (pixel index 1 = ink, 0 = transparent), and prints a C array
`nb_font[]` (char c uses tile index c-32) for pasting into runtime.c. Also writes
a scaled preview PNG. Run once at authoring time; the output is committed.

    tools/gen_gba_font.py [preview.png]
"""
import sys
from PIL import Image, ImageFont, ImageDraw

FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
FIRST, LAST = 32, 126


def glyph_rows(font, ch):
    img = Image.new("L", (8, 8), 0)
    ImageDraw.Draw(img).text((0, -1), ch, fill=255, font=font)
    px = img.load()
    return [sum((1 << x) for x in range(8) if px[x, y] > 110) for y in range(8)]


def main():
    font = ImageFont.truetype(FONT, 9)
    tiles = []                     # u16 stream, 16 per glyph
    rows_by_ch = {}
    for code in range(FIRST, LAST + 1):
        rows = glyph_rows(font, chr(code))
        rows_by_ch[code] = rows
        for y in range(8):
            for half in range(2):
                v = 0
                for k in range(4):
                    if rows[y] & (1 << (half * 4 + k)):
                        v |= 1 << (k * 4)      # pixel index 1 = ink
                tiles.append(v)
    # C array
    print("/* built-in 8x8 text font (ASCII %d..%d), 4bpp; char c -> tile c-%d.\n"
          "   Generated by tools/gen_gba_font.py. */" % (FIRST, LAST, FIRST))
    print("#define NB_FONT_FIRST %d" % FIRST)
    print("#define NB_FONT_COUNT %d" % (LAST - FIRST + 1))
    body = ", ".join("0x%04X" % v for v in tiles)
    print("static const u16 nb_font[] = { %s };" % body)

    # preview
    out = sys.argv[1] if len(sys.argv) > 1 else "/tmp/font_preview.png"
    sample = "HELLO WORLD! Hero HP:20/100 Lv.3 <Press A>"
    sc = 6
    im = Image.new("RGB", (len(sample) * 8 * sc, 8 * sc), (16, 20, 30))
    pp = im.load()
    for ci, ch in enumerate(sample):
        c = ord(ch)
        if not (FIRST <= c <= LAST):
            continue
        rows = rows_by_ch[c]
        for y in range(8):
            for x in range(8):
                if rows[y] & (1 << x):
                    for sy in range(sc):
                        for sx in range(sc):
                            pp[(ci * 8 + x) * sc + sx, y * sc + sy] = (240, 240, 210)
    im.save(out)
    sys.stderr.write("preview -> %s\n" % out)


if __name__ == "__main__":
    main()
